name: chores_app
description: Your App to get your chores done.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.1
  flutter_gen: ^3.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  firebase_core: ^1.4.0
  firebase_analytics: ^8.2.0
  firebase_auth: ^3.0.1
  cloud_firestore: ^2.4.0
  firebase_messaging: ^10.0.4
  firebase_crashlytics: ^2.1.1
  splash_screen_view: ^3.0.0
  google_fonts: ^2.1.0
  flutter_rating_bar: ^4.0.0
  adaptive_theme: ^2.2.0
  google_sign_in: ^5.0.4
  shared_preferences: ^2.0.6

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
fonts:
  - family: NunitoSans
    fonts:
      - asset: assets/fonts/NunitoSans-Light.ttf
        weight: 300
      - asset: assets/fonts/NunitoSans-Regular.ttf
        weight: 400
      - asset: assets/fonts/NunitoSans-SemiBold.ttf
        weight: 500
      - asset: assets/fonts/NunitoSans-Bold.ttf
        weight: 600
      - asset: assets/fonts/NunitoSans-Black.ttf
        weight: 700
flutter_intl:
  enabled: true
